//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentACar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inspecciones
    {
        public int Id { get; set; }
        public int TipoInspeccion { get; set; }
        public int Vehiculo { get; set; }
        public int Cliente { get; set; }
        public int Empleado { get; set; }
        public bool Ralladuras { get; set; }
        public int NivelCombustible { get; set; }
        public bool GomaRespuesta { get; set; }
        public bool Gato { get; set; }
        public bool RoturasCristal { get; set; }
        public bool GomaDelanteraDerecha { get; set; }
        public bool GomaDelanteraIzquierda { get; set; }
        public bool GomaTraseraDerecha { get; set; }
        public bool GomaTraseraIzquierda { get; set; }
        public System.DateTime Fecha { get; set; }
    }
}
