//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentACar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rentas
    {
        public int Id { get; set; }
        public int Empleado { get; set; }
        public int Vehiculo { get; set; }
        public int Cliente { get; set; }
        public Nullable<System.DateTime> FechaRenta { get; set; }
        public Nullable<int> InspeccionRenta { get; set; }
        public Nullable<int> FechaDevolucion { get; set; }
        public Nullable<int> InspeccionDevolucion { get; set; }
        public decimal MontoDiario { get; set; }
        public int CantidadDias { get; set; }
        public string Comentario { get; set; }
        public int Estado { get; set; }
    }
}
