//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentACar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehiculos
    {
        public int Id { get; set; }
        public string NoChasis { get; set; }
        public string NoPlaca { get; set; }
        public string NoMotor { get; set; }
        public int TipoVehiculo { get; set; }
        public int Marca { get; set; }
        public int Modelo { get; set; }
        public int TipoCombustible { get; set; }
        public int Estado { get; set; }
        public bool Deleted { get; set; }
    
        public virtual CombustiblesTipos CombustiblesTipos { get; set; }
        public virtual Marcas Marcas { get; set; }
        public virtual Modelos Modelos { get; set; }
        public virtual VehiculosTipos VehiculosTipos { get; set; }
    }
}
